### ISSUE TITLE
check autograder fail always fails

### ISSUE THREAD

**Issue by orbeckst** [markpatterson27/Simple-SQL-Exercise#1]
The line
https://github.com/markpatterson27/Simple-SQL-Exercise/blob/a412c0fe4d2fbfeba7a55cabb06e7f8e6a72fad1/.github/workflows/classroom.yml#L89 always marks the action as failed, even if the autograder was a success.

**Comment by orbeckst** [comment]
p.s.: @markpatterson27 thank you so much for sharing your recipe, it's really helpful to give student immediate visual feedback through the badge

(I started using classroom and used your approach https://github.com/ASU-CompMethodsPhysics-PHY494/activity-03-python_calculator)

**Comment by markpatterson27** [comment]
Thanks @orbeckst. I caught this when creating course exercises, but forgot to update it here. There's several possible values for outcome. I'm thinking !success is a better condition to trigger job failure on, but it depends what sort of feedback you want to give students.

Your python calc exercise looks good. (Now I'm wondering if there's a way to use an action to convert LaTex to png and insert it back into the README 🤔)

**Comment by orbeckst** [comment]
On second thought I agree with your suggestion to rather use `if ${{ steps.autograder.outcome != 'success' }}` given the [other possible values](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#steps-context). When I changed it I thought I'd keep it as simple as possible (and it took me a while to figure out GH actions...) but better not to show success when, e.g., the job was 'canceled'.

Re: inserting png or svg via actions: Let me know if you happen to have a solution, I'd be interested ;-).
